package fr.diginamic.recensement.menu;

/**
 * Type de traitement
 * 
 * @author RichardBONNAMY
 *
 */
public enum TypeTraitement {
	/** RECHERCHE_POP_VILLE */
	RECHERCHE_POP_VILLE,
	/** RECHERCHE_POP_DEPT */
	RECHERCHE_POP_DEPT,
	/** RECHERCHE_POP_REGION */
	RECHERCHE_POP_REGION,
	/** RECHERCHE_N_VILLES_DEPT */
	RECHERCHE_N_VILLES_DEPT,
	/** RECHERCHE_N_VILLES_REGION */
	RECHERCHE_N_VILLES_REGION,
	/** RECHERCHE_N_DEPTS */
	RECHERCHE_N_DEPTS,
	/** RECHERCHE_N_REGIONS */
	RECHERCHE_N_REGIONS,
	/** RECHERCHE_N_VILLES_FRANCE */
	RECHERCHE_N_VILLES_FRANCE;
}
